version: '3.8'
services:
  backend:
    build: ./server
    restart: unless-stopped
    env_file: server/.env
  frontend:
    build: ./client
    env_file: client/.env
    ports:
      - 3000:3000

volumes:
  db:
